name: my-docker-project

services:
  app:
    build: .
    container_name: my-docker-container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - pgbouncer

  postgres:
    image: postgres:17
    container_name: postgres-container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DATABASE = postgres
    env_file:
      - ./.env

  pgbouncer:
    image: edoburu/pgbouncer:1.18.0
    container_name: pgbouncer-container
    restart: always
    ports:
      - "6432:6432"
    depends_on:
      - postgres
    env_file:
      - ./.env


volumes:
  postgres_data: