name: my-docker-project

services:
  app:
    build: .
    container_name: my-docker-container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres-container
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


volumes:
  postgres_data: